version: '3.4'

services:
  redis:
    image: redis:alpine
  web:
    image: restaurant
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    ports:
      - 5000:5000
    volumes:
      - .:/code
