version: '3.4'

services:
  redis:
    image: redis:alpine
#    hostname: redis
#    ports:
#      - 6379:6379
#    volumes:
#      - ./config/redis.conf:/redis.conf
#    command: [ "redis-server", "/redis.conf" ]


  web:
    image: restaurant
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    ports:
      - 5000:5000
    volumes:
      - .:/code
